/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuis;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.awt.event.KeyEvent;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GENDERGROUP = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfnik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taalamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbmembaca = new javax.swing.JCheckBox();
        cbmenulis = new javax.swing.JCheckBox();
        cbolahraga = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbpendidikan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ftftgllahir = new javax.swing.JFormattedTextField();
        ftfipk = new javax.swing.JFormattedTextField();
        BTNDaftar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tftlp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        tfnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnikActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat");

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });

        taalamat.setColumns(20);
        taalamat.setRows(5);
        jScrollPane1.setViewportView(taalamat);

        jLabel4.setText("Jenis Kelamin");

        GENDERGROUP.add(rblaki);
        rblaki.setText("Laki-Laki");
        rblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakiActionPerformed(evt);
            }
        });

        GENDERGROUP.add(rbperempuan);
        rbperempuan.setText("Perempuan");

        jLabel5.setText("Hobi");

        cbmembaca.setText("Membaca");
        cbmembaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmembacaActionPerformed(evt);
            }
        });

        cbmenulis.setText("Menulis");

        cbolahraga.setText("Olah Raga");

        jLabel6.setText("Tanggal Lahir");

        jLabel7.setText("Pendidikan");

        cbpendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4 / S1", "S2", "S3" }));
        cbpendidikan.setSelectedIndex(-1);
        cbpendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpendidikanActionPerformed(evt);
            }
        });

        jLabel8.setText("IPK");

        ftftgllahir.setText("yyyy-mm-dd");
        ftftgllahir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftftgllahirFocusLost(evt);
            }
        });
        ftftgllahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftftgllahirActionPerformed(evt);
            }
        });

        ftfipk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfipkFocusLost(evt);
            }
        });
        ftfipk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfipkActionPerformed(evt);
            }
        });

        BTNDaftar.setText("DAFTAR");
        BTNDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDaftarActionPerformed(evt);
            }
        });

        jLabel9.setText("No.tlp");

        tftlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftlpActionPerformed(evt);
            }
        });
        tftlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tftlpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnik, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(rblaki)
                        .addGap(18, 18, 18)
                        .addComponent(rbperempuan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftlp)
                            .addComponent(ftftgllahir)
                            .addComponent(cbpendidikan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbmembaca, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbmenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbolahraga, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNDaftar))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ftfipk))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rblaki)
                    .addComponent(rbperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tftlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbmembaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmenulis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbolahraga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftftgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ftfipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNDaftar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnikActionPerformed

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void rblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblakiActionPerformed

    private void cbmembacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmembacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmembacaActionPerformed

    private void ftfipkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfipkActionPerformed
        try {
        String selectedText = ftfipk.getSelectedText();

            if (selectedText != null && !selectedText.isEmpty()) {
                double ipk = Double.parseDouble(selectedText);
                Object pendidikan = cbpendidikan.getSelectedItem();

                // Validasi nilai IPK dalam rentang 0.00 - 4.00
                if (ipk < 0.00 || ipk > 4.00) {
                    JOptionPane.showMessageDialog(null, "IPK tidak valid. Masukkan nilai antara 0.00 hingga 4.00.");
                } else if (ipk < 3.01 && "D1".equals(pendidikan)) {
                    JOptionPane.showMessageDialog(null, "IPK tidak memenuhi minimal untuk pendidikan D1.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada IPK yang dipilih.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "IPK yang dimasukkan tidak valid.");
        }
    }//GEN-LAST:event_ftfipkActionPerformed

    private void cbpendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpendidikanActionPerformed
        Object pendidikan = cbpendidikan.getSelectedItem();
        if(pendidikan == null){
            JOptionPane.showMessageDialog(null, "Pendidikan harus diisi");
        }if (pendidikan == "SD" || pendidikan == "SMP" || pendidikan == "SMA"){
            JOptionPane.showMessageDialog(null, "Pendidikan minimal tidak memenuhi syarat");
        }
    }//GEN-LAST:event_cbpendidikanActionPerformed

    private void tftlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftlpActionPerformed

    private void tftlpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tftlpKeyPressed
        char inputChar = evt.getKeyChar();
        if(!Character.isDigit(inputChar)&& inputChar != KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(null, "input harus angka");
        }
    }//GEN-LAST:event_tftlpKeyPressed

    private void ftfipkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfipkFocusLost
        try {
        String inputText = ftfipk.getText().trim(); // Ambil teks penuh dari field

        if (!inputText.isEmpty()) {
            double ipk = Double.parseDouble(inputText);
            Object pendidikan = cbpendidikan.getSelectedItem();
            if (ipk < 0.00 || ipk > 4.00) {
                JOptionPane.showMessageDialog(null, "IPK tidak valid. Masukkan nilai antara 0.00 hingga 4.00.");
                ftfipk.requestFocus(); 
            } else if (ipk < 3.01 && "D1".equals(pendidikan)) {
                JOptionPane.showMessageDialog(null, "IPK tidak memenuhi minimal untuk pendidikan D1.");
                ftfipk.requestFocus(); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan nilai IPK.");
            ftfipk.requestFocus(); 
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "IPK yang dimasukkan tidak valid. Masukkan angka desimal.");
        ftfipk.requestFocus(); 
    }
    }//GEN-LAST:event_ftfipkFocusLost

    private void ftftgllahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftftgllahirActionPerformed
        

    }//GEN-LAST:event_ftftgllahirActionPerformed

    private void ftftgllahirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftftgllahirFocusLost
        try {
        String tanggalLahirText = ftftgllahir.getText().trim();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate tanggalLahir = LocalDate.parse(tanggalLahirText, formatter);

        LocalDate sekarang = LocalDate.now();
        int umur = Period.between(tanggalLahir, sekarang).getYears();

        if (umur < 18) {
            JOptionPane.showMessageDialog(null, "Usia tidak memenuhi syarat. Minimal 18 tahun.");
            ftftgllahir.requestFocus(); 
        }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal tidak valid. Gunakan format yyyy-MM-dd.");
            ftftgllahir.requestFocus(); 
        }
    }//GEN-LAST:event_ftftgllahirFocusLost

    private void BTNDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDaftarActionPerformed
        if(tfnik.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "NIK Kosong");
        }
        if(tfnama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Kosong");
        }
        if(taalamat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Kosong");
        }
        if(GENDERGROUP.getSelection()== null){
            JOptionPane.showMessageDialog(null, "Gender Kosong");
        }
        if(tftlp.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No Tlp.Kosong");
        }
        
        if(ftftgllahir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tanggal Lahir Kosong");
        }
        Object pendidikan = cbpendidikan.getSelectedItem();
        if(pendidikan == null){
            JOptionPane.showMessageDialog(null, "Pendidikan kosong");
        }
        if(ftfipk.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "IPK Kosong");
        }
        
        JOptionPane.showMessageDialog(null, "Pendaftaran Berhasil");
        
        tfnik.setText(""); 
        tfnama.setText(""); 
        taalamat.setText(""); 
        GENDERGROUP.clearSelection();
        tftlp.setText(""); 
        cbmembaca.setSelected(false);
        cbmenulis.setSelected(false);
        cbolahraga.setSelected(false);
        ftftgllahir.setText(""); 
        cbpendidikan.setSelectedIndex(-1); 
        ftfipk.setText(""); 
    }//GEN-LAST:event_BTNDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDaftar;
    private javax.swing.ButtonGroup GENDERGROUP;
    private javax.swing.JCheckBox cbmembaca;
    private javax.swing.JCheckBox cbmenulis;
    private javax.swing.JCheckBox cbolahraga;
    private javax.swing.JComboBox<String> cbpendidikan;
    private javax.swing.JFormattedTextField ftfipk;
    private javax.swing.JFormattedTextField ftftgllahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTextArea taalamat;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnik;
    private javax.swing.JTextField tftlp;
    // End of variables declaration//GEN-END:variables

    private void elseif(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
